### ISSUE TITLE
vignette("cyclomort") # Warning message: vignette ‘cyclomort’ not found 

### ISSUE THREAD

**Issue by DrMattG** [EliGurarie/cyclomort#45]
Hello, I am looking to make use of your package which looks great. I wanted to open the vignette in my R session but get a message saying it is not found (Warning message: vignette ‘cyclomort’ not found). I am not sure if this is a devtools issue. I will get the vignette from here but thought you might not know about this issue. 

Cheers
Matt

```
library(devtools)
install_github("https://github.com/EliGurarie/cyclomort", vignettes = TRUE)
library(cyclomort)
vignette("cyclomort")

```

**Comment by EliGurarie** [comment]
Hi Matt, 
Thanks for pointing this out ... it's curious that the vignette doesn't install.  I'll look into this. 
I am hoping to upload this package to CRAN soon, and will more or less have to fix those issues. 
Do let us know how well cyclomort works for your purposes!
- Elie

**Comment by EliGurarie** [comment]
Vignette should install now.  Highly unscientific process to get it to work. 
Am finally attempting to release this on CRAN.
